travis:
  secure:
    BINSTAR_TOKEN: ZmZDs7ytScx44fa7W6KaEUeYvtFJCMW9/jMQS6sF/0kgBKyGJZ3S6rF7t+mfxMJkHJbLUmD13LdRDJ9J0kgUO6BJdnepl+Y5SsU3oWH7zcbbdfiZA2ZcUj8eqi0l6gcNRI6NYxCX//bhdv/iqS0VY9gWGLVRBWqvBVKCw8097k+VILNlCSeAMZsVrHq8iyyAqjeFIK8j8NKtvlgfV0sIoc5cm081AjmHVMVjKWOU3AcPXQFOL0fwgw1Ij8Vj8TWPakZO/QDJBF1lwF6XQPJv0gYoDyb2PhrkEoVO7EjW3QrvvJmKUDhN10pyIG/x4RqjCShOAuhjL1Aw53Czsmnn5ijihovkuhIuP1nMhyav9LHi/CAgv2+58Gq/vixz6Jt1bmEKyYZz7ZisSGi5ibN15G32jzUpTYF15U5w5Tyc7/3xnpTNY+AziGFFqGtDRvtZEMlWK/c24KevtrSwR8D1WX4k0m//NSrr2cBHepD6PRi0UaVbGyhxoF0eLGi4igtFbvyGKfWPrXBRYlTvjun/w6MIoFIoryv845KHcxemrvoc/4vXjLTgH1kXveeiS2MM1wfo0wT1sQOPOYExpXP6Mo1ytnegM3sAiC3VozwGxbtxSRXKPdrEuXjUsS6vTwSVrXqXuyTA0ewHp+G3+jFLVD3tGjK+Z49a2o+CyQwJf4Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
